Upload video added
a-legotin/InstaSharper pull request #176
Opened 2018-04-02 10:58 UTC by ramtinak

2018-04-02 16:00 UTC, a-legotin commented on InstaSharper/Classes/VideoUploadJobResponse.cs
> +    //{
remove commented code in every place in this PR

2018-04-02 16:00 UTC, a-legotin commented on InstaSharper/API/Processors/MediaProcessor.cs
> +                var instaUri = UriCreator.GetUploadVideoUri();
please make sure that your changes at least correctly build, before creating pull request:
```
error CS0117: 'UriCreator' does not contain a definition for 'GetUploadVideoUri'
```

2018-04-02 16:00 UTC, a-legotin requested changes
All checks have failed
+ couple of comments

2018-04-03 10:29 UTC, ramtinak commented
Please remove this commit or at least close it.

2018-04-10 09:05 UTC, closed without merging